// Entity aliases from CLAUDE.md — maps alternate names to canonical article titles
// Update this when new aliases are discovered during ingestion

export const ENTITY_ALIASES: Record<string, string> = {
  'Chemical and Volume Control System': 'CVCS',
  'Boration Systems': 'CVCS',
  'charging and letdown': 'CVCS',
  'Reactor Coolant System': 'RCS',
  'Thermal-Hydraulic Design': 'RCS',
  'thermal hydraulic design': 'RCS',
  'T-H design': 'RCS',
  'DNB': 'RCS',
  'DNBR': 'RCS',
  'Reactor Coolant Pumps': 'RCPs',
  'RCP': 'RCPs',
  'Steam Generators': 'Steam Generator & Blowdown',
  'SGs': 'Steam Generator & Blowdown',
  'SG': 'Steam Generator & Blowdown',
  'Pressurizer': 'Pressurizer & PRT',
  'PZR': 'Pressurizer & PRT',
  'PZR control': 'Pressurizer Level & Press Control',
  'pressurizer control': 'Pressurizer Level & Press Control',
  'Reactor Vessel': 'Rx Vessel & Internals',
  'RPV': 'Rx Vessel & Internals',
  'RV': 'Rx Vessel & Internals',
  'reactor core': 'Rx Vessel & Internals',
  'fuel assemblies': 'Rx Vessel & Internals',
  'Reactor Core and Fuel': 'Rx Vessel & Internals',
  'Nuclear Design': 'Rx Vessel & Internals',
  'nuclear design parameters': 'Rx Vessel & Internals',
  'reactivity coefficients': 'Rx Vessel & Internals',
  'fuel rods': 'Rx Vessel & Internals',
  'fuel handling ventilation': 'FHV',
  'refueling operations': 'Refueling',
  'reactor vessel level indication system': 'RVLIS',
  'ECCS': 'Emergency Core Cooling Systems',
  'safety injection': 'Emergency Core Cooling Systems',
  'CFCUs': 'Containment Fan Coil Units',
  'containment cooling': 'Containment Fan Coil Units',
  'RHR': 'Residual Heat Removal',
  'shutdown cooling': 'Residual Heat Removal',
  'CCW': 'Component Cooling Water',
  'SW': 'Service Water',
  'AFW': 'Auxiliary Feedwater',
  'PORVs': 'Power Operated Relief Valves',
  'loss of RHR': 'AB.RHR-0001 — Loss of RHR',
  'ATWS response': 'EOP-FRSM-1 — Response to Nuclear Power Generation',
  'response to nuclear power generation': 'EOP-FRSM-1 — Response to Nuclear Power Generation',
  'SG tube leak': 'AB.SG-0001 — Steam Generator Tube Leak',
  'NIS malfunction': 'AB.NIS-0001 — Nuclear Instrumentation System Malfunction',
  'control room evacuation': 'AB.CR-0001 — Control Room Evacuation',
  'rapid load reduction': 'AB.LOAD-0001 — Rapid Load Reduction',
  'inadequate core cooling': 'EOP-FRCC-1 — Response to Inadequate Core Cooling',
  'SG overpressure': 'EOP-FRHS-2 — Response to Steam Generator Overpressure',
  'adverse containment': 'Adverse Containment',
  'adverse containment conditions': 'Adverse Containment',
};
