// Entity aliases from CLAUDE.md — maps alternate names to canonical article titles
// Update this when new aliases are discovered during ingestion

export const ENTITY_ALIASES: Record<string, string> = {
  'Chemical and Volume Control System': 'CVCS',
  'Boration Systems': 'CVCS',
  'charging and letdown': 'CVCS',
  'Reactor Coolant System': 'RCS',
  'Thermal-Hydraulic Design': 'RCS',
  'thermal hydraulic design': 'RCS',
  'T-H design': 'RCS',
  'DNB': 'RCS',
  'DNBR': 'RCS',
  'Reactor Coolant Pumps': 'RCPs',
  'RCP': 'RCPs',
  'Steam Generators': 'Steam Generator & Blowdown',
  'SGs': 'Steam Generator & Blowdown',
  'SG': 'Steam Generator & Blowdown',
  'Pressurizer': 'Pressurizer & PRT',
  'PZR': 'Pressurizer & PRT',
  'PZR control': 'Pressurizer Level & Press Control',
  'pressurizer control': 'Pressurizer Level & Press Control',
  'Reactor Vessel': 'Rx Vessel & Internals',
  'RPV': 'Rx Vessel & Internals',
  'RV': 'Rx Vessel & Internals',
  'reactor core': 'Rx Vessel & Internals',
  'fuel assemblies': 'Rx Vessel & Internals',
  'Reactor Core and Fuel': 'Rx Vessel & Internals',
  'Nuclear Design': 'Rx Vessel & Internals',
  'nuclear design parameters': 'Rx Vessel & Internals',
  'reactivity coefficients': 'Rx Vessel & Internals',
  'fuel rods': 'Rx Vessel & Internals',
  'fuel handling ventilation': 'FHV',
  'refueling operations': 'Refueling',
  'reactor vessel level indication system': 'RVLIS',
  'ECCS': 'ECCS',
  'safety injection': 'ECCS',
  'SI': 'ECCS',
  'CFCUs': 'CFCUs',
  'containment cooling': 'CFCUs',
  'containment fan coolers': 'CFCUs',
  'RHR': 'RHR',
  'shutdown cooling': 'RHR',
  'CCW': 'CCW',
  'SW': 'Service Water',
  'AFW': 'AFW',
  'PORVs': 'Pressurizer & PRT',
  'loss of RHR': 'AB.RHR-0001 — Loss of RHR',
  'ATWS response': 'EOP-FRSM-1 — Response to Nuclear Power Generation',
  'response to nuclear power generation': 'EOP-FRSM-1 — Response to Nuclear Power Generation',
  'SG tube leak': 'AB.SG-0001 — Steam Generator Tube Leak',
  'NIS malfunction': 'AB.NIS-0001 — Nuclear Instrumentation System Malfunction',
  'control room evacuation': 'AB.CR-0001 — Control Room Evacuation',
  'rapid load reduction': 'AB.LOAD-0001 — Rapid Load Reduction',
  'inadequate core cooling': 'EOP-FRCC-1 — Response to Inadequate Core Cooling',
  'SG overpressure': 'EOP-FRHS-2 — Response to Steam Generator Overpressure',
  'adverse containment': 'Containment',
  'adverse containment conditions': 'Containment',
  'Containment Systems': 'Containment',
  'containment isolation': 'Containment',
  'Instrumentation and Controls': 'RPS/SSPS',
  'I&C': 'RPS/SSPS',
  'reactor trip system': 'RPS/SSPS',
  'RTS': 'RPS/SSPS',
  'ESFAS': 'RPS/SSPS',
  'reactor protection': 'RPS/SSPS',
  'solid state protection': 'RPS/SSPS',
  'nuclear instruments': 'Excore NIs',
  'NIS': 'Excore NIs',
  'excore detectors': 'Excore NIs',
  'CRDM': 'Control Rod Drive',
  'rod control': 'Control Rod Drive',
  'process radiation monitors': 'Radiation Monitoring',
  'rad monitors': 'Radiation Monitoring',
  'Radiation Protection': 'Radiation Monitoring',
  'rad protection': 'Radiation Monitoring',
  'ALARA': 'Radiation Monitoring',
  'shielding': 'Radiation Monitoring',
  'incore flux mapping': 'Incores',
  'CETs': 'Incores',
  'subcooling margin monitor': 'Incores',
  'ATWS Mitigation System': 'AMSAC',
  'ATWS mitigation': 'AMSAC',
  'Diesel Generators': 'EDGs',
  'EDG': 'EDGs',
  'emergency diesel generators': 'EDGs',
  'Feedwater and Condensate': 'Feed & Condensate',
  'feedwater': 'Feed & Condensate',
  'main feedwater': 'Feed & Condensate',
  'condensate': 'Feed & Condensate',
  'Turbine-Generator': 'Main Turbine',
  'turbine generator': 'Main Turbine',
  'T/G': 'Main Turbine',
  'Auxiliary Feedwater': 'AFW',
  'auxiliary feedwater system': 'AFW',
  'Radioactive Waste Management': 'Waste Gas',
  'rad waste': 'Waste Gas',
  'AC Power': '500KV',
  'offsite power': '500KV',
  'switchyard': '500KV',
  'Component Cooling Water': 'CCW',
  'Residual Heat Removal': 'RHR',
  'Emergency Core Cooling Systems': 'ECCS',
  'Containment Fan Coil Units': 'CFCUs',
  'condenser steam dumps': 'Steam Dumps',
  'steam dump valves': 'Steam Dumps',
  'MSIVs': 'Main Steam',
  'main steam system': 'Main Steam',
  'containment spray': 'Containment Spray',
  'SCW': 'Stator Cooling Water',
  'service air': 'Control Air',
  'station air': 'Control Air',
  'OHA': 'Annunciators',
  'overhead annunciators': 'Annunciators',
  'nat circ without RVLIS': 'EOP-TRIP-6 — Natural Circulation Cooldown Without RVLIS',
  'on-the-spot change': 'AD-AA-101-101 — OTSC Process',
  'OTSC': 'AD-AA-101-101 — OTSC Process',
  'equipment tagging': 'OP-AA-109-115 — Equipment Tagging',
  'red blocking tag': 'OP-AA-109-115 — Equipment Tagging',
  'confined space': 'SA-AA-114 — Confined Space Program',
  'shift turnover': 'OP-AA-112-101 — Shift Turnover and Relief',
  'reactivity management': 'OP-AA-300 — Reactivity Management',
  'NRC reporting': 'SECG — Reportable Action Levels (RAL)',
  'reportable action levels': 'SECG — Reportable Action Levels (RAL)',
  'high radiation area': 'RP-AA-460 — Controls for High and Very High Radiation Areas',
  'locked high radiation area': 'RP-AA-460 — Controls for High and Very High Radiation Areas',
  'fire brigade staffing': 'FP-AA-012 — Fire Brigade Staffing',
  'loss of all service water': 'AB.SW-0005 — Loss of All Service Water',
  'core alteration': 'S2.OP-IO.ZZ-0007 — Cold Shutdown to Refueling',
  'cold shutdown to refueling': 'S2.OP-IO.ZZ-0007 — Cold Shutdown to Refueling',
  'communications': 'OP-AA-104-101 — Communications',
};
