// Entity aliases from CLAUDE.md — maps alternate names to canonical article titles
// Update this when new aliases are discovered during ingestion

export const ENTITY_ALIASES: Record<string, string> = {
  'CVCS': 'Chemical and Volume Control System',
  'Boration Systems': 'Chemical and Volume Control System',
  'charging and letdown': 'Chemical and Volume Control System',
  'RCS': 'Reactor Coolant System',
  'ECCS': 'Emergency Core Cooling Systems',
  'safety injection': 'Emergency Core Cooling Systems',
  'CFCUs': 'Containment Fan Coil Units',
  'containment cooling': 'Containment Fan Coil Units',
  'RHR': 'Residual Heat Removal',
  'shutdown cooling': 'Residual Heat Removal',
  'CCW': 'Component Cooling Water',
  'SW': 'Service Water',
  'AFW': 'Auxiliary Feedwater',
  'PORVs': 'Power Operated Relief Valves',
  'loss of RHR': 'AB.RHR-0001 — Loss of RHR',
  'ATWS response': 'EOP-FRSM-1 — Response to Nuclear Power Generation',
  'response to nuclear power generation': 'EOP-FRSM-1 — Response to Nuclear Power Generation',
  'SG tube leak': 'AB.SG-0001 — Steam Generator Tube Leak',
  'NIS malfunction': 'AB.NIS-0001 — Nuclear Instrumentation System Malfunction',
  'control room evacuation': 'AB.CR-0001 — Control Room Evacuation',
  'rapid load reduction': 'AB.LOAD-0001 — Rapid Load Reduction',
  'inadequate core cooling': 'EOP-FRCC-1 — Response to Inadequate Core Cooling',
  'SG overpressure': 'EOP-FRHS-2 — Response to Steam Generator Overpressure',
  'adverse containment': 'Adverse Containment',
  'adverse containment conditions': 'Adverse Containment',
};
